---

spark_group: hadoop
spark_users:
  - mapred

spark_conf_dir: /etc/spark/conf

spark_conf:
  install_dir: /opt/spark
  no_hadoop:
    url: https://d3kbcqa49mib13.cloudfront.net/spark-2.2.0-bin-without-hadoop.tgz
    file: spark-2.2.0-bin-without-hadoop.tgz
    basename: spark-2.2.0-bin-without-hadoop
  with_hadoop:
    url: https://d3kbcqa49mib13.cloudfront.net/spark-2.2.0-bin-hadoop2.7.tgz
    file: spark-2.2.0-bin-hadoop2.7.tgz
    basename: spark-2.2.0-bin-hadoop2.7